Fix compilation of tests with cl
the cl ci was failing with this error:

D:\a\WGVK\WGVK\tests\wgvk_unit_tests.cpp(860,32): error C7555: use of designated initializers requires at least '/std:c++20' [D:\a\WGVK\WGVK\build\unit_tests.vcxproj]

Tell CMake to use C++20 on this file to fix it.